# Generated by Django 5.2.1 on 2025-09-28 17:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('requestingdept', models.CharField(choices=[('Administration', 'Administration'), ('Finance', 'Finance'), ('Programs', 'Programs'), ('Human Resource', 'Human Resource'), ('Communications', 'Communications')], max_length=100)),
                ('projectname', models.CharField(choices=[('Ending Gender Based Violence', 'Ending Gender Based Violence'), ('Building ECDs', 'Building ECDs')], max_length=100)),
                ('projectcode', models.CharField(choices=[('GBV2025', 'GBV2025'), ('ECD2025', 'ECD2025')], max_length=100)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUBMITTED', max_length=50)),
                ('staffid', models.CharField(default='frezer', null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL))),
                ('activityname', models.CharField(max_length=50)),
                ('accountnumber', models.CharField(default='6565', max_length=20, null=True)),
                ('createdby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requisitionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='SUBMITTED', max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=50)),
                ('requisitionid', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='SUBMITTED', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=50)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/')),
                ('proofofpay', models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/')),
                ('participantspay', models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/')),
                ('cashpay', models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/')),
                ('requisitionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition')),
                ('voucherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ED', 'ED'), ('Programs Manager', 'Programs Manager'), ('Programs Coordinator', 'Programs Coordinator'), ('Project Officer', 'Project Officer'), ('Finance Officer', 'Finance Officer'), ('M & E Officer', 'M & E Officer'), ('Field Officer', 'Field Officer')], max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
