# Generated by Django 5.2.1 on 2025-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='projectcode',
            field=models.CharField(choices=[('GBV2025', 'GBV2025'), ('ECD2025', 'ECD2025')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='projectname',
            field=models.CharField(choices=[('Ending Gender Based Violence', 'Ending Gender Based Violence'), ('Building ECDs', 'Building ECDs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requestingdept',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Finance', 'Finance'), ('Programs', 'Programs'), ('Human Resource', 'Human Resource'), ('Communications', 'Communications')], max_length=100),
        ),
    ]
