# Generated by Django 5.2.1 on 2025-06-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='accountnumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='staffid',
            field=models.CharField(null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=10),
        ),
    ]
