# Generated by Django 5.2.1 on 2025-07-02 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0003_alter_requisition_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='requisitionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='requisitionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='voucherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CashTracker.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='requisitionid',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='CashTracker.requisition'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='staffid',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
