# Generated by Django 5.2.1 on 2025-07-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0004_alter_item_requisitionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='staffid',
        ),
    ]
