# Generated by Django 5.2.1 on 2025-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0005_remove_voucher_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirement',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=10),
        ),
    ]
