# Generated by Django 5.2.1 on 2025-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0006_retirement_status_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='createdby',
            field=models.CharField(default='george', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retirement',
            name='createdby',
            field=models.CharField(default='george', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='createdby',
            field=models.CharField(default='george', max_length=50),
            preserve_default=False,
        ),
    ]
