# Generated by Django 5.2.1 on 2025-07-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0007_requisition_createdby_retirement_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirement',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='CashTracke/retirements/'),
        ),
    ]
