# Generated by Django 5.2.1 on 2025-07-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0008_retirement_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirement',
            name='cashpay',
            field=models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='participantspay',
            field=models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='proofofpay',
            field=models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='CashTracker/retirements/'),
        ),
    ]
