# Generated by Django 5.2.1 on 2025-08-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTracker', '0009_retirement_cashpay_retirement_participantspay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=50),
        ),
    ]
